import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const resp = await fetch(process.env.NEXT_PUBLIC_API_URL + "topics");
  const data = await resp.json();
  return (
    <html lang="en">
      <body>
        <h1>
          <a href="/">Web</a>
        </h1>
        <ol>
          {/* @ts-ignore */}
          {data.map((topic) => (
            <li>
              <a href={`/read/${topic.id}`}>{topic.title}</a>
            </li>
          ))}
        </ol>
        {children}
        <ul>
          <li>
            <a href="/create">create</a>
          </li>
          <li>
            <a href="/update/1">update</a>
          </li>
          <li>
            <button>delete</button>
          </li>
        </ul>
      </body>
    </html>
  );
}
